version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 0s
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: main
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"